name: Check Branch Before Merge

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR is from develop
        run: |
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "PRs to main must come from develop branch."
            exit 1
          fi
